export { default as Menu } from './menu/Menu';
export { loader as menuLoader } from './menu/Menu';
export { default as Cart } from './cart/Cart';
export { default as CreateOrder } from './order/CreateOrder';
export { default as Order } from './order/Order';
export { default as SearchOrder } from './order/SearchOrder';
export { loader as orderLoader } from './order/Order';
export { action as createOrderAction } from './order/CreateOrder';
export { default as CreateUser } from './user/CreateUser';
export { default as CartItem } from './cart/CartItem';
export { default as OrderItem } from './order/OrderItem';
// import Menu, { loader as menuLoader } from './features/menu/Menu';
